

#### Introduction #####

# these are a set of functions which are used to read .edat files from the SUCCAB cognitive
# testing computers and translate them into properly formatted excel/SPSS data sets. This file
# is the backend for the 'reading SUCCAB R script' file, which actually executes the functions.
# Only use this script to adjust the behaviour of the functions themselves, otherwise the 
# reading SUCCAB R script is used to actually read and translate the SUCCAB data. 

# This code is quite poorly documented at this stage but I will be giving it greater detail 
# if we determine this will be used further in the future. 

# Load packages

library(tidyverse)
library("rprime")
library("wrapr")


#### read data ####

# A function to prepare all eprime data simultaneously
reduce_wm <- function(wm_path) {
  
  # Read in text file generated by Eprime
  wm_lines <- read_eprime(wm_path, remove_clock = F)
  
  # Convert lines from Eprime file into EprimeFrame objects
  wm_frames <- FrameList(wm_lines)
  
  # Make it a data frame.
  succab <- to_data_frame(wm_frames)
}


#### process sequence C scores ####

extract_C <- function(df) {
  
  ## CRT
  
  # RT
  
  CRT_RT <- df %>% 
    select(matches("CRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RT")), ~ "CRT_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select(ID, everything())
  
  # ACC
  
  CRT_ACC <- df %>% 
    select(matches("CRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>%  
    tally() %>% 
    mutate(CRT_acc = n/20 * 100) %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select(-n) %>% 
    select(ID, everything())
  
  
  ## SWT

  # RT
  SWT_RT <- df %>% 
    select(matches("SWT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    mutate(across(ends_with("RT"), mean, na.rm = TRUE, 
                  .names = "SWT_overall_RT")) %>% 
    group_by(across(ends_with("RESP"))) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    rename_at(vars(ends_with(".RT")), ~ "SWTRT") %>%
    pivot_wider(names_from = novel_original, 
                names_prefix = "SWTRT_", 
                values_from = SWTRT) %>% 
    rename_at(vars(ends_with("_2")), ~ "SWT_original_RT") %>% 
    rename_at(vars(ends_with("_3")), ~ "SWT_novel_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'SWT_overall_RT', 
    'SWT_original_RT', 'SWT_novel_RT')) %>% 
    select(ID, everything())
  
  # ACC 

  SWT_ACC <- df %>% 
    select(matches("SWT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    group_by(across(ends_with("original"))) %>%  
    tally() %>% 
    mutate(SWTacc = n / 28 * 100) %>% 
    select(-n) %>% 
    pivot_wider(names_from = novel_original,
                values_from = SWTacc,
                names_prefix = "SWTacc_") %>% 
    mutate(SWT_overall_acc = rowMeans(.,na.rm=T)) %>% 
    rename_at(vars(ends_with("_2")), ~ "SWT_original_acc") %>% 
    rename_at(vars(ends_with("_3")), ~ "SWT_novel_acc") %>%
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'SWT_original_acc',
                              'SWT_novel_acc', 'SWT_overall_acc')) %>% 
    select(ID, everything())
  
  
  ## DRT ##
  
  # RT 

  DRT_RT <- df %>% 
    select(matches("DRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    mutate(across(ends_with("RT"), mean, na.rm = TRUE, 
                  .names = "DRT_overall_RT")) %>% 
    group_by(across(ends_with("RESP"))) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    rename_at(vars(ends_with(".RT")), ~ "DRTRT") %>%
    pivot_wider(names_from = novel_original, 
                names_prefix = "DRTRT_", 
                values_from = DRTRT) %>% 
    rename_at(vars(ends_with("_2")), ~ "DRT_original_RT") %>% 
    rename_at(vars(ends_with("_3")), ~ "DRT_novel_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'DRT_overall_RT', 
                              'DRT_original_RT', 'DRT_novel_RT')) %>% 
    select(ID, everything())
  
  # acc 

  DRT_ACC <- df %>% 
    select(matches("DRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    group_by(across(ends_with("original"))) %>%  
    tally() %>% 
    ## SEQUENCE C ONLY ##
    mutate(DRT_acc = if_else(novel_original == 2,
                             n / 14 * 100,
                             n / 15 * 100)) %>%
    mutate(DRT_overall_acc = sum(n) / 29 * 100) %>% 
    select(-n) %>% 
    pivot_wider(names_from = novel_original,
                values_from = DRT_acc,
                names_prefix = "DRTacc_") %>% 
    rename_at(vars(ends_with("_2")), ~ "DRT_original_acc") %>% 
    rename_at(vars(ends_with("_3")), ~ "DRT_novel_acc") %>%
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'DRT_overall_acc', 
                              'DRT_original_acc', 'DRT_novel_acc')) %>% 
    select(ID, everything())
  
  
  ## SRT 
  
  # RT
  
  SRT_RT <- df %>% 
    select(matches("SRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    mutate(across(ends_with("RT"), mean, na.rm = TRUE, 
                  .names = "SRT_overall_RT")) %>% 
    group_by(across(ends_with("RESP"))) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    rename_at(vars(ends_with(".RT")), ~ "SRTRT") %>%
    pivot_wider(names_from = novel_original, 
                names_prefix = "SRTRT_", 
                values_from = SRTRT) %>% 
    rename_at(vars(ends_with("_2")), ~ "SRT_original_RT") %>% 
    rename_at(vars(ends_with("_3")), ~ "SRT_novel_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'SRT_original_RT', 
                              'SRT_novel_RT', 'SRT_overall_RT')) %>% 
    select(ID, everything())
  
  # ACC
  
  SRT_ACC <- df %>% 
    select(matches("SRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    group_by(across(ends_with("original"))) %>%  
    tally() %>% 
    mutate(SRTacc = n / 15 * 100) %>% 
    select(-n) %>% 
    pivot_wider(names_from = novel_original,
                values_from = SRTacc,
                names_prefix = "SRTacc_") %>% 
    mutate(SRT_overall_acc = rowMeans(.,na.rm=T)) %>% 
    rename_at(vars(ends_with("_2")), ~ "SRT_original_acc") %>% 
    rename_at(vars(ends_with("_3")), ~ "SRT_novel_acc") %>%
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'SRT_original_acc', 
                              'SRT_novel_acc', 'SRT_overall_acc')) %>% 
    select(ID, everything())
  
  ## ST1T 
  
  # RT 

  ST1T_RT <- df %>% 
    select(matches("ST1T[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RT")), ~ "ST1T_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select(ID, everything())
  
  # ACC
  
  ST1T_ACC <- df %>% 
    select(matches("ST1T[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>%  
    tally() %>% 
    mutate(ST1T_acc = n/40 * 100) %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select(-n) %>% 
    select(ID, everything())
  
  ## ST2T
  
  # RT
  
  ST2T_RT <- df %>% 
    select(matches("ST2T[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RT")), ~ "ST2T_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select(ID, everything())
  
  
  # ACC 
  
  ST2T_ACC <- df %>% 
    select(matches("ST2T[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>%  
    tally() %>% 
    mutate(ST2T_acc = n/40 * 100) %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select(-n) %>% 
    select(ID, everything())
  
  # Merge all the files 
  
  out <- SWT_RT %>% 
    full_join(SWT_ACC, by = 'ID') %>% 
    full_join(CRT_RT, by = 'ID') %>%
    full_join(CRT_ACC, by = 'ID') %>%
    full_join(DRT_RT, by = 'ID') %>%
    full_join(DRT_ACC, by = 'ID') %>%
    full_join(SRT_RT, by = 'ID') %>%
    full_join(SRT_ACC, by = 'ID') %>%
    full_join(ST1T_RT, by = 'ID') %>%
    full_join(ST1T_ACC, by = 'ID') %>%
    full_join(ST2T_RT, by = 'ID') %>%
    full_join(ST2T_ACC, by = 'ID')
}


extract <- function(df) {
  
  ## CRT
  
  # RT
  
  CRT_RT <- df %>% 
    select(matches("CRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RT")), ~ "CRT_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select(ID, everything())
  
  # ACC
  
  CRT_ACC <- df %>% 
    select(matches("CRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>%  
    tally() %>% 
    mutate(CRT_acc = n/20 * 100) %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select(-n) %>% 
    select(ID, everything())
  
  
  
  ## SWT
  
  # RT
  
  SWT_RT <- df %>% 
    select(matches("SWT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    mutate(across(ends_with("RT"), mean, na.rm = TRUE, 
                  .names = "SWT_overall_RT")) %>% 
    group_by(across(ends_with("RESP"))) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    rename_at(vars(ends_with(".RT")), ~ "SWTRT") %>%
    pivot_wider(names_from = novel_original, 
                names_prefix = "SWTRT_", 
                values_from = SWTRT) %>% 
    rename_at(vars(ends_with("_2")), ~ "SWT_original_RT") %>% 
    rename_at(vars(ends_with("_3")), ~ "SWT_novel_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'SWT_overall_RT', 
                              'SWT_original_RT', 'SWT_novel_RT')) %>% 
    select(ID, everything())
  
  # ACC 
  
  SWT_ACC <- df %>% 
    select(matches("SWT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    group_by(across(ends_with("original"))) %>%  
    tally() %>% 
    mutate(SWTacc = n / 28 * 100) %>% 
    select(-n) %>% 
    pivot_wider(names_from = novel_original,
                values_from = SWTacc,
                names_prefix = "SWTacc_") %>% 
    mutate(SWT_overall_acc = rowMeans(.,na.rm=T)) %>% 
    rename_at(vars(ends_with("_2")), ~ "SWT_original_acc") %>% 
    rename_at(vars(ends_with("_3")), ~ "SWT_novel_acc") %>%
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'SWT_original_acc',
                              'SWT_novel_acc', 'SWT_overall_acc')) %>% 
    select(ID, everything())
  
  
  ## DRT ##
  
  # RT 
  
  DRT_RT <- df %>% 
    select(matches("DRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    mutate(across(ends_with("RT"), mean, na.rm = TRUE, 
                  .names = "DRT_overall_RT")) %>% 
    group_by(across(ends_with("RESP"))) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    rename_at(vars(ends_with(".RT")), ~ "DRTRT") %>%
    pivot_wider(names_from = novel_original, 
                names_prefix = "DRTRT_", 
                values_from = DRTRT) %>% 
    rename_at(vars(ends_with("_2")), ~ "DRT_original_RT") %>% 
    rename_at(vars(ends_with("_3")), ~ "DRT_novel_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'DRT_overall_RT', 
                              'DRT_original_RT', 'DRT_novel_RT')) %>% 
    select(ID, everything())
  
  # acc 
  
  DRT_ACC <- df %>% 
    select(matches("DRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    group_by(across(ends_with("original"))) %>%  
    tally() %>% 
    ## SEQUENCE 3 ONLY ##
    mutate(DRT_acc = n / 15 * 100) %>% 
    select(-n) %>% 
    pivot_wider(names_from = novel_original,
                values_from = DRT_acc,
                names_prefix = "DRTacc_") %>% 
    mutate(DRT_overall_acc = rowMeans(.,na.rm=T)) %>% 
    rename_at(vars(ends_with("_2")), ~ "DRT_original_acc") %>% 
    rename_at(vars(ends_with("_3")), ~ "DRT_novel_acc") %>%
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'DRT_overall_acc', 
                              'DRT_original_acc', 'DRT_novel_acc')) %>% 
    select(ID, everything())
  
  
  ## SRT 
  
  # RT
  
  SRT_RT <- df %>% 
    select(matches("SRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    mutate(across(ends_with("RT"), mean, na.rm = TRUE, 
                  .names = "SRT_overall_RT")) %>% 
    group_by(across(ends_with("RESP"))) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    rename_at(vars(ends_with(".RT")), ~ "SRTRT") %>%
    pivot_wider(names_from = novel_original, 
                names_prefix = "SRTRT_", 
                values_from = SRTRT) %>% 
    rename_at(vars(ends_with("_2")), ~ "SRT_original_RT") %>% 
    rename_at(vars(ends_with("_3")), ~ "SRT_novel_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'SRT_original_RT', 
                              'SRT_novel_RT', 'SRT_overall_RT')) %>% 
    select(ID, everything())
  
  # ACC
  
  SRT_ACC <- df %>% 
    select(matches("SRT[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$"),
           str_subset(colnames(.), "stim.RESP$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    rename_at(vars(ends_with("RESP")), ~ "novel_original") %>%
    group_by(across(ends_with("original"))) %>%  
    tally() %>% 
    mutate(SRTacc = n / 15 * 100) %>% 
    select(-n) %>% 
    pivot_wider(names_from = novel_original,
                values_from = SRTacc,
                names_prefix = "SRTacc_") %>% 
    mutate(SRT_overall_acc = rowMeans(.,na.rm=T)) %>% 
    rename_at(vars(ends_with("_2")), ~ "SRT_original_acc") %>% 
    rename_at(vars(ends_with("_3")), ~ "SRT_novel_acc") %>%
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select_if(names(.) %in% c('ID', 'SRT_original_acc', 
                              'SRT_novel_acc', 'SRT_overall_acc')) %>% 
    select(ID, everything())
  
  ## ST1T 
  
  # RT 
  
  ST1T_RT <- df %>% 
    select(matches("ST1T[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RT")), ~ "ST1T_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select(ID, everything())
  
  # ACC
  
  ST1T_ACC <- df %>% 
    select(matches("ST1T[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>%  
    tally() %>% 
    mutate(ST1T_acc = n/40 * 100) %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select(-n) %>% 
    select(ID, everything())
  
  ## ST2T
  
  # RT
  
  ST2T_RT <- df %>% 
    select(matches("ST2T[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>% 
    summarise(across(ends_with("RT"), ~ mean(., na.rm=T))) %>% 
    rename_at(vars(ends_with("RT")), ~ "ST2T_RT") %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), n = length(.))) %>% 
    select(ID, everything())
  
  
  # ACC 
  
  ST2T_ACC <- df %>% 
    select(matches("ST2T[0-9]")) %>% 
    select(str_subset(colnames(.), ".RT$"), 
           str_subset(colnames(.), ".ACC$")) %>% 
    mutate_all(as.numeric) %>% 
    filter(across(ends_with("ACC"), ~. > 0)) %>% 
    filter(across(ends_with("RT"), ~. > 150)) %>%  
    tally() %>% 
    mutate(ST2T_acc = n/40 * 100) %>% 
    mutate(ID = rep(unique(df$Eprime.Basename), 
                    n = length(.))) %>% 
    select(-n) %>% 
    select(ID, everything())
  
  # Merge all the files 
  
  out <- SWT_RT %>% 
    full_join(SWT_ACC, by = 'ID') %>% 
    full_join(CRT_RT, by = 'ID') %>%
    full_join(CRT_ACC, by = 'ID') %>%
    full_join(DRT_RT, by = 'ID') %>%
    full_join(DRT_ACC, by = 'ID') %>%
    full_join(SRT_RT, by = 'ID') %>%
    full_join(SRT_ACC, by = 'ID') %>%
    full_join(ST1T_RT, by = 'ID') %>%
    full_join(ST1T_ACC, by = 'ID') %>%
    full_join(ST2T_RT, by = 'ID') %>%
    full_join(ST2T_ACC, by = 'ID')
}


#### Choose between sequence C or other sequences ####

extract_scores <- function(df){
  group <- unique(gsub("SUCCAB_ARCLI_SEQUENCE_(.).*", 
                       "\\1",
                       df$Eprime.Basename))
  
  if (group == "C"){
    extract_C(df)
  } else {
    extract(df)
  }
}




#### Coalesce join ####

coalesce_join <- function(x, y, 
                          by = NULL, suffix = c(".x", ".y"), 
                          join = dplyr::full_join, ...) {
  joined <- full_join(x, y, by = "IDno", suffix = c(".x", ".y"))
  # names of desired output
  cols <- union(names(x), names(y))
  
  to_coalesce <- names(joined)[!names(joined) %in% cols]
  suffix_used <- suffix[ifelse(endsWith(to_coalesce, suffix[1]), 1, 2)]
  # remove suffixes and deduplicate
  to_coalesce <- unique(substr(
    to_coalesce, 
    1, 
    nchar(to_coalesce) - nchar(suffix_used)
  ))
  
  coalesced <- purrr::map_dfc(to_coalesce, ~dplyr::coalesce(
    joined[[paste0(.x, suffix[1])]], 
    joined[[paste0(.x, suffix[2])]]
  ))
  names(coalesced) <- to_coalesce
  
  dplyr::bind_cols(joined, coalesced)[cols]
}
